services:
  - type: web
    name: ai-playground-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ORIGIN_ALLOWLIST
        value: https://ai-playground-web.onrender.com
      - key: SERVER_API_KEY
        generateValue: true
  - type: web
    name: ai-playground-web
    env: static
    buildCommand: cd client && npm ci && VITE_API_BASE_URL="https://$API_HOST" npm run build
    staticPublishPath: client/dist
    envVars:
      - key: API_HOST
        fromService:
          type: web
          name: ai-playground-api
          property: host
